version: '3'

services:
  zeppelin9:
    image: ${USERNAME}/zeppelin-custom-0.9.0:3.1.2-hadoop3.2-java11-bdb
    container_name: zeppelin9
    hostname: zeppelin9
    networks:
      - spark-net
    volumes:
      - ./notebook_9:/opt/zeppelin/notebook
      - ./logs_9:/opt/zeppelin/logs
      - ./conf_9:/opt/zeppelin/conf
      - work:/share
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.zeppelin.rule=Host(`zeppelin9.bdb`)"
    #  - "traefik.http.services.zeppelin.loadbalancer.server.port=8080"

  zeppelin10:
    image: ${USERNAME}/zeppelin-custom-0.10.0:3.1.2-hadoop3.2-java11-bdb
    container_name: zeppelin10
    hostname: zeppelin10
    networks:
      - spark-net
    volumes:
      - ./notebook_10:/opt/zeppelin/notebook
      - ./logs_10:/opt/zeppelin/logs
      - ./conf_10:/opt/zeppelin/conf
      - work:/share
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zeppelin.rule=Host(`zeppelin10.bdb`)"
      - "traefik.http.services.zeppelin.loadbalancer.server.port=8080"

networks:
  spark-net:
    external:
      name: spark-net

volumes:
  work:
    external:
      name: work
